Multi object handling
SoMa-Project/ec_grasp_planner pull request #26
Opened 2018-05-08 14:27 UTC by zweistein

The library implements multi-object handling with heuristic functions. Tested in simulation with Kuka system and one object as there is no reliable multi-object detection integrated into master.

2018-05-09 14:25 UTC, asieverling requested changes

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/data/object_param.yaml
> +  letuch:
should be lettuce

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +from tornado.concurrent import return_future
remove import

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +        h = -1
what's this? please change variable name or add a comment

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +        # distance form EC (wall end edge)
from

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +    #object-envirtionment-hand based heuristic valeu for grasping
object-environment-hand based heuristic value for grasping
 
            
  Write

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +        # max_probability_dict = {k:v for k,v in h_matrix.items() if float(v) == max_probability}
can you remove this code?

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +        ideces_sampled_max = self.sample_from_pdf(h_matrix)
what does this variable name mean?

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +                print("The givne hand {} and object {} has no parameters set in the yaml {}".format(hand_type, o["type"], self.file_name))
given

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/planner.py
> +        object_frame.header.stamp = time # TODO why do we need to change the time in the header?
answer: graph and object should have the exact same timestamp so that you can use tf to convert between them.

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/planner.py
> +        # this should catch if the framse in the graph and objects are not in the same reference frame
remove this code if check is not needed anymore

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/planner.py
> +        # we assume that all objects are on the same plain, so all EC can be exploited for any of the objects
plain -> plane

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/planner.py
> +            # camera_in_base = self.tf_listener.asMatrix(robot_base_frame, chosen_object.header)
remove

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/data/object_param.yaml
> +      EdgeGrasp: {'success': 0.25}
can you add disney objects?

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/data/object_param.yaml
> +    RBOHandO2WAM:
please add default settings

2018-05-09 14:25 UTC, asieverling commented on ec_grasp_planner/src/multi_object_params.py
> +            object_index,  ec_index = self.argmax_h(h_matrix)
this should be deterministic, i.e. return first element with highest value

2018-05-09 14:55 UTC, zweistein commented on ec_grasp_planner/data/object_param.yaml
> +  letuch:
done

2018-05-09 15:04 UTC, zweistein commented on ec_grasp_planner/data/object_param.yaml
> +    RBOHandO2WAM:
removed hand type, this should be handled in the planner through the object_param_file argument

2018-05-09 15:34 UTC, zweistein reviewed
items with "done" text were handled in the commit

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +        h = -1
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +    #object-envirtionment-hand based heuristic valeu for grasping
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +        # max_probability_dict = {k:v for k,v in h_matrix.items() if float(v) == max_probability}
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +        ideces_sampled_max = self.sample_from_pdf(h_matrix)
done, and only the first max is returned deterministically

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +                print("The givne hand {} and object {} has no parameters set in the yaml {}".format(hand_type, o["type"], self.file_name))
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/multi_object_params.py
> +            object_index,  ec_index = self.argmax_h(h_matrix)
done in the function

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/planner.py
> +        object_frame.header.stamp = time # TODO why do we need to change the time in the header?
Ok, I might miss this from the new feature.

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/planner.py
> +        # this should catch if the framse in the graph and objects are not in the same reference frame
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/planner.py
> +        # we assume that all objects are on the same plain, so all EC can be exploited for any of the objects
done

2018-05-09 15:34 UTC, zweistein commented on ec_grasp_planner/src/planner.py
> +            # camera_in_base = self.tf_listener.asMatrix(robot_base_frame, chosen_object.header)
dene

2018-05-23 12:59 UTC, zweistein commented
@asieverling changes are integrated and tested in simulation. Please review it again.

2018-05-23 13:26 UTC, asieverling reviewed
Code is ok, however some documentation should be added both to ec_grasp_planner and soma_utils

2018-05-23 14:41 UTC, asieverling approved these changes

2018-05-23 14:42 UTC, merged